ALTER TABLE t_p19837706_microloan_landing_pr.leads 
ADD COLUMN IF NOT EXISTS first_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS last_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS amount INTEGER,
ADD COLUMN IF NOT EXISTS days INTEGER,
ADD COLUMN IF NOT EXISTS source VARCHAR(100);